### ISSUE TITLE
Students add their own page in the Student folder!

### ISSUE THREAD

**Issue by rishabh-bansal** [rishabh-bansal/Make-a-Pull-Request#1]

**Comment by RaiVaibhav** [comment]
@rishabh-bansal  i added my own its showing conflicts

**Comment by nikhilbansal97** [comment]
@rishabh-bansal we have to add our page as md file and create pr..is that right?

**Comment by SrijanJha28** [comment]
Hi I would like to work on this issue.

**Comment by rishabh-bansal** [comment]
@SrijanJha28 @nikhilbansal97 Go ahead!

**Comment by maykillmore** [comment]
I'd like to take this up

**Comment by rishabh-bansal** [comment]
Everyone is free to take up this issue! :)
Just do leave your comments here if you find it useful! :)

**Comment by chaostools** [comment]
added myself #453

**Comment by christophermoura** [comment]
Hi @rishabh-bansal!

Could you review the commit [#505](https://github.com/rishabh-bansal/Make-a-Pull-Request/pull/505)? Thank you!

**Comment by devutsav** [comment]
@rishabh-bansal kindly review and merge #662

**Comment by MatheusRV** [comment]
I believe the description may be better, a lot are leaving the root or are forgetting to add the .md extension, we can make a template available and let you better describe how to create the file.
