### ISSUE TITLE
Hmm, what about GDPR?

### ISSUE THREAD

**Issue by tarlepp** [rishabh-bansal/Make-a-Pull-Request#1307]
You're collection some person data, so who are you handling GDPR requirements?

**Comment by jesuiscamille** [comment]
I think it's more like a Github problem.

**Comment by praveenscience** [comment]
@tarlepp It's the users, who consent themselves to give their details. So it's not a problem. 😄

**Comment by rishabh-bansal** [comment]
@praveenscience 👍
