### ISSUE TITLE
Hacktoberfest 2018 

### ISSUE THREAD

**Issue by tarlepp** [rishabh-bansal/Make-a-Pull-Request#1309]
IMHO

Repositories like this _isn't_ really helping the Open Source community - why this Hacktoberfest event is created.

So creating repositories like this to just "harvest" pull request is just wrong - it's really sad to see that people are just using these repositories to gain something - when they really aren't adding anything to original cause...

**Comment by rishabh-bansal** [comment]
@tarlepp I made this repository for beginners to learn about Git and GitHub, currently, I'm not able to maintain it. If you have something useful for beginners you can add it up here. 😄
