### ISSUE TITLE
Add your name to CONTRIBUTING.md after adding a student page!

### ISSUE THREAD

**Issue by rishabh-bansal** [rishabh-bansal/Make-a-Pull-Request#2]

**Comment by SrijanJha28** [comment]
I would like to work on this.

**Comment by mustorze** [comment]
Hey #89

**Comment by Rishabh42** [comment]
Would like to take this up..

**Comment by ShreyasheeS** [comment]
I claim.

**Comment by rishabh-bansal** [comment]
Everyone is free to take up this issue! :)

**Comment by rishabh-bansal** [comment]
Everyone is free to take up this issue! :)
Just do leave your comments here if you find it useful! :)

**Comment by chaostools** [comment]
added myself to contributing.md .do merge. this was a nice first project to work upon .[#453](https://github.com/rishabh-bansal/Make-a-Pull-Request/pull/453)

**Comment by niftyken** [comment]
I created a new file in Students, then added, committed, pushed to origin, and submitted a pull request. Then I modified the CONTRIBUTORS file to have my name as well a few minutes later. Do I submit a separate pull request for this additional file? This is all pretty new to me, thanks!
