### ISSUE TITLE
Does anyone know how to merge '250 Pull Requests' at once? :|

### ISSUE THREAD

**Issue by rishabh-bansal** [rishabh-bansal/Make-a-Pull-Request#363]

**Comment by MichaelDeBoey** [comment]
I'm afraid that's not possible 😕

**Comment by jesuiscamille** [comment]
May you can add me as contributor, I'ld like to help =)

**Comment by rishabh-bansal** [comment]
@jesuiscamille Added! :)

**Comment by jesuiscamille** [comment]
39 pull requests awaiting and a lot to re-open ( merge conflicts )

**Comment by rishabh-bansal** [comment]
@jesuiscamille  Thanks for you help! You were great! :)

**Comment by jesuiscamille** [comment]
=)

**Comment by jesuiscamille** [comment]
now, 8 pull requests are for you. I'll add mine.
